%module ClientDLL

%{
    /* 在包装代码中包含头文件 */
    #include "DataItem.h"
    #include "ClientWarp.h"
    
%}
%typemap(ctype)  void* "void *"
%typemap(imtype) void* "System.IntPtr"
%typemap(cstype) void* "System.IntPtr"
%typemap(csin)   void* "$csinput"
%typemap(in)     void* %{ $1 = $input; %}
%typemap(out)    void* %{ $result = $1; %}
%typemap(csout, excode = SWIGEXCODE)  void*{
    System.IntPtr cPtr = $imcall; $excode
    return cPtr;
}
%typemap(csvarout, excode = SWIGEXCODE2) void* %{
    get {
        System.IntPtr cPtr = $imcall; $excode
        return cPtr;
   }
%}
/* 解析头文件生成包装代码 */
%include "DataItem.h"
%include "ClientWarp.h"
