//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class DataItem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DataItem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DataItem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DataItem() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClientDLLPINVOKE.delete_DataItem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int protocol {
    set {
      ClientDLLPINVOKE.DataItem_protocol_set(swigCPtr, value);
    } 
    get {
      int ret = ClientDLLPINVOKE.DataItem_protocol_get(swigCPtr);
      return ret;
    } 
  }

  public int bufferLength {
    set {
      ClientDLLPINVOKE.DataItem_bufferLength_set(swigCPtr, value);
    } 
    get {
      int ret = ClientDLLPINVOKE.DataItem_bufferLength_get(swigCPtr);
      return ret;
    } 
  }

  public System.IntPtr GetBuffer() {
    System.IntPtr cPtr = ClientDLLPINVOKE.DataItem_GetBuffer(swigCPtr); 
    return cPtr;
}

  public long SetBuffer(System.IntPtr ptr) {
    long ret = ClientDLLPINVOKE.DataItem_SetBuffer(swigCPtr, ptr);
    return ret;
  }

  public int ByteRead(System.IntPtr ptr) {
    int ret = ClientDLLPINVOKE.DataItem_ByteRead(swigCPtr, ptr);
    return ret;
  }

  public DataItem() : this(ClientDLLPINVOKE.new_DataItem(), true) {
  }

}
