// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef PROTOBUF_INCLUDED_Protocol_2eproto
#define PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Protocol_2eproto();
namespace Message {
class KeyChange;
class KeyChangeDefaultTypeInternal;
extern KeyChangeDefaultTypeInternal _KeyChange_default_instance_;
class KeyData;
class KeyDataDefaultTypeInternal;
extern KeyDataDefaultTypeInternal _KeyData_default_instance_;
}  // namespace Message
namespace google {
namespace protobuf {
template<> ::Message::KeyChange* Arena::CreateMaybeMessage<::Message::KeyChange>(Arena*);
template<> ::Message::KeyData* Arena::CreateMaybeMessage<::Message::KeyData>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Message {

// ===================================================================

class KeyData final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Message.KeyData) */ {
 public:
  KeyData();
  virtual ~KeyData();

  KeyData(const KeyData& from);

  inline KeyData& operator=(const KeyData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KeyData(KeyData&& from) noexcept
    : KeyData() {
    *this = ::std::move(from);
  }

  inline KeyData& operator=(KeyData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const KeyData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyData* internal_default_instance() {
    return reinterpret_cast<const KeyData*>(
               &_KeyData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(KeyData* other);
  friend void swap(KeyData& a, KeyData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KeyData* New() const final {
    return CreateMaybeMessage<KeyData>(nullptr);
  }

  KeyData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<KeyData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const KeyData& from);
  void MergeFrom(const KeyData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::int32 key() const;
  void set_key(::google::protobuf::int32 value);

  // required int32 keyState = 2;
  bool has_keystate() const;
  void clear_keystate();
  static const int kKeyStateFieldNumber = 2;
  ::google::protobuf::int32 keystate() const;
  void set_keystate(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.KeyData)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 key_;
  ::google::protobuf::int32 keystate_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class KeyChange final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Message.KeyChange) */ {
 public:
  KeyChange();
  virtual ~KeyChange();

  KeyChange(const KeyChange& from);

  inline KeyChange& operator=(const KeyChange& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KeyChange(KeyChange&& from) noexcept
    : KeyChange() {
    *this = ::std::move(from);
  }

  inline KeyChange& operator=(KeyChange&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const KeyChange& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyChange* internal_default_instance() {
    return reinterpret_cast<const KeyChange*>(
               &_KeyChange_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(KeyChange* other);
  friend void swap(KeyChange& a, KeyChange& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KeyChange* New() const final {
    return CreateMaybeMessage<KeyChange>(nullptr);
  }

  KeyChange* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<KeyChange>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const KeyChange& from);
  void MergeFrom(const KeyChange& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyChange* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Message.KeyData keyDatas = 1;
  int keydatas_size() const;
  void clear_keydatas();
  static const int kKeyDatasFieldNumber = 1;
  ::Message::KeyData* mutable_keydatas(int index);
  ::google::protobuf::RepeatedPtrField< ::Message::KeyData >*
      mutable_keydatas();
  const ::Message::KeyData& keydatas(int index) const;
  ::Message::KeyData* add_keydatas();
  const ::google::protobuf::RepeatedPtrField< ::Message::KeyData >&
      keydatas() const;

  // @@protoc_insertion_point(class_scope:Message.KeyChange)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Message::KeyData > keydatas_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// KeyData

// required int32 key = 1;
inline bool KeyData::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void KeyData::clear_key() {
  key_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 KeyData::key() const {
  // @@protoc_insertion_point(field_get:Message.KeyData.key)
  return key_;
}
inline void KeyData::set_key(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  key_ = value;
  // @@protoc_insertion_point(field_set:Message.KeyData.key)
}

// required int32 keyState = 2;
inline bool KeyData::has_keystate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void KeyData::clear_keystate() {
  keystate_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 KeyData::keystate() const {
  // @@protoc_insertion_point(field_get:Message.KeyData.keyState)
  return keystate_;
}
inline void KeyData::set_keystate(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  keystate_ = value;
  // @@protoc_insertion_point(field_set:Message.KeyData.keyState)
}

// -------------------------------------------------------------------

// KeyChange

// repeated .Message.KeyData keyDatas = 1;
inline int KeyChange::keydatas_size() const {
  return keydatas_.size();
}
inline void KeyChange::clear_keydatas() {
  keydatas_.Clear();
}
inline ::Message::KeyData* KeyChange::mutable_keydatas(int index) {
  // @@protoc_insertion_point(field_mutable:Message.KeyChange.keyDatas)
  return keydatas_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Message::KeyData >*
KeyChange::mutable_keydatas() {
  // @@protoc_insertion_point(field_mutable_list:Message.KeyChange.keyDatas)
  return &keydatas_;
}
inline const ::Message::KeyData& KeyChange::keydatas(int index) const {
  // @@protoc_insertion_point(field_get:Message.KeyChange.keyDatas)
  return keydatas_.Get(index);
}
inline ::Message::KeyData* KeyChange::add_keydatas() {
  // @@protoc_insertion_point(field_add:Message.KeyChange.keyDatas)
  return keydatas_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Message::KeyData >&
KeyChange::keydatas() const {
  // @@protoc_insertion_point(field_list:Message.KeyChange.keyDatas)
  return keydatas_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Protocol_2eproto
